#!/usr/bin/env bash

#  Copyright 2018-2019 Banco Bilbao Vizcaya Argentaria, S.A.
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Deployment options
CGO_LDFLAGS_ALLOW='.*'
QED="go run $GOPATH/src/github.com/bbva/qed/main.go"

$QED generate signerkeys

# Server options
LEADER_CONFIG=()
LEADER_CONFIG+=('--log debug')
LEADER_CONFIG+=('--api-key key')
LEADER_CONFIG+=('--db-path /var/tmp/qed${i}/db')
LEADER_CONFIG+=('--gossip-addr 127.0.0.1:840${i}')
LEADER_CONFIG+=('--http-addr 127.0.0.1:880${i}')
LEADER_CONFIG+=('--metrics-addr 127.0.0.1:860${i}')
LEADER_CONFIG+=('--mgmt-addr 127.0.0.1:870${i}')
LEADER_CONFIG+=('--node-id ${i}')
LEADER_CONFIG+=('--private-key-path /var/tmp/qed_ed25519')
LEADER_CONFIG+=('--raft-addr 127.0.0.1:850${i}')
LEADER_CONFIG+=('--raft-path /var/tmp/qed${i}/wal')
LEADER_CONFIG+=('--enable-profiling')
LEADER_CONFIG+=('--profiling-addr 127.0.0.1:606${i}')

FOLLOWER_CONFIG=("${LEADER_CONFIG[@]}")
FOLLOWER_CONFIG+=('--raft-join-addr 127.0.0.1:8701')
FOLLOWER_CONFIG+=('--gossip-join-addr 127.0.0.1:8401')


# Port 6060 conflict if followers and leader have the following option enabled.
LEADER_CONFIG+=('--enable-profiling')

if ! which envsubst
then
    echo -e "Please install envsubst. OSX -> brew install gettext ; brew link --force gettext"
    exit 1
fi

# Start leader
leader=$(echo ${LEADER_CONFIG[@]} | i=1 envsubst )
mkdir -p /var/tmp/qed-pids /var/tmp/qed-log-1
$QED server start $leader > /var/tmp/qed-log-1/server.log 2>&1 &
echo $! > /var/tmp/qed-pids/qed-log-1.pid
echo -e "\n See Qed server logs at /var/tmp/qed-log-1/server.log \n"
sleep 3s

# Get num followers.
followers="$1"
if [ -z $followers ]; then
	followers=0
	echo -e "\n Starting QED standalone \n"
else
	# Start followers
	for id in $(seq 2 `expr $followers + 1`); do
		mkdir -p /var/tmp/qed-log-${id}
		follower=$(echo ${FOLLOWER_CONFIG[@]} | i=$id envsubst )
		$QED server start $follower > /var/tmp/qed-log-${id}/server.log 2>&1 &
		echo $! > /var/tmp/qed-pids/qed-log-${id}.pid
		echo -e "\n See Qed follower-${id} logs at /var/tmp/qed-log-${id}/server.log \n"
		sleep 3s
	done
fi


